name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS region'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v1   
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: ${{ inputs.region }}    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="mansi.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="mansi.tfvars"


    
